export const SEARCH_RECIPES = 'SEARCH_RECIPES';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const GET_DETAILS = 'GET_DETAILS';
export const GET_DETAILS_FAILED = 'GET_DETAILS_FAILED';
export const LOADING = 'LOADING';
